"""add device_serial_numbers to groups

Revision ID: 1e889c72d5ce
Revises: ce5b4402ee63
Create Date: 2026-07-11 13:44:40.079244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e889c72d5ce'
down_revision: Union[str, Sequence[str], None] = 'ce5b4402ee63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('device_serial_numbers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'device_serial_numbers')
    # ### end Alembic commands ###
