"""drop roles, replace user role_id with permissions

Revision ID: 9b6b9673053e
Revises: 9003455e7d81
Create Date: 2026-06-27 22:39:27.543494

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9b6b9673053e"
down_revision: Union[str, Sequence[str], None] = "9003455e7d81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("name"), table_name="roles")
    op.drop_table("roles")
    op.add_column("users", sa.Column("permissions", sa.JSON(), nullable=False))
    op.drop_column("users", "role_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role_id",
            mysql.INTEGER(display_width=11),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "permissions")
    op.create_table(
        "roles",
        sa.Column(
            "id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False
        ),
        sa.Column("name", mysql.VARCHAR(length=50), nullable=False),
        sa.Column("description", mysql.VARCHAR(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("name"), "roles", ["name"], unique=True)
    # ### end Alembic commands ###
