"""baseline schema

Revision ID: e4a9cfcc56aa
Revises:
Create Date: 2026-08-15 14:27:45.737652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.domains.profiles import models as profile_models
from app.infra.core import types as app_types


# revision identifiers, used by Alembic.
revision: str = "e4a9cfcc56aa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("serial_number", sa.String(length=30), nullable=False),
        sa.Column("os_version", sa.String(length=20), nullable=False),
        sa.Column(
            "connection_status",
            sa.Enum("CONNECTED", "DISCONNECTED", "UNKNOWN", name="connectionstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ENROLLED", "UNENROLLED", "PENDING", "UNKNOWN", name="devicestatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("last_enrolled_at", sa.DateTime(), nullable=False),
        sa.Column("battery_status", sa.Integer(), nullable=True),
        sa.Column("total_storage", sa.Integer(), nullable=True),
        sa.Column("available_storage", sa.Integer(), nullable=True),
        sa.Column("total_memory", sa.Integer(), nullable=True),
        sa.Column("available_memory", sa.Integer(), nullable=True),
        sa.Column("network", app_types.NetworkInfoType(), nullable=True),
        sa.Column("certificates", app_types.CertificateListType(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_index("ix_devices_connection_status", "devices", ["connection_status"], unique=False)
    op.create_index("ix_devices_os_version", "devices", ["os_version"], unique=False)
    op.create_index("ix_devices_status", "devices", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("permissions", app_types.PermissionListType(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "commands",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column(
            "command_type",
            sa.Enum(
                "CHECK_IN",
                "LOCK",
                "UNLOCK",
                "WIPE",
                "RESTART",
                "SHUTDOWN",
                name="commandtype",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "ACKNOWLEDGED",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="commandstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("result_message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("rabbitmq_message_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_commands_command_type", "commands", ["command_type"], unique=False)
    op.create_index("ix_commands_device_id", "commands", ["device_id"], unique=False)
    op.create_index("ix_commands_status", "commands", ["status"], unique=False)
    op.create_table(
        "extension_attributes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "data_type",
            sa.Enum("STRING", "INTEGER", "DATE", name="extensiondatatype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "input_type",
            sa.Enum("TEXT_FIELD", "POPUP_MENU", name="extensioninputtype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("popup_choices", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_extension_attributes_created_by", "extension_attributes", ["created_by"], unique=False)
    op.create_table(
        "inventory_searches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_inventory_searches_created_by", "inventory_searches", ["created_by"], unique=False)
    op.create_table(
        "mobile_apps",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("package_version", sa.String(length=32), nullable=False),
        sa.Column("package_name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("scope", profile_models.ScopeColumnType(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("policy", profile_models.PolicyColumnType(), nullable=False),
        sa.Column("scope", profile_models.ScopeColumnType(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_profiles_created_by", "profiles", ["created_by"], unique=False)
    op.create_table(
        "smart_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("criteria", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_smart_groups_created_by", "smart_groups", ["created_by"], unique=False)
    op.create_table(
        "static_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "device_extension_attribute_values",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("extension_attribute_id", sa.Integer(), nullable=False),
        sa.Column("extension_attribute_name", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["extension_attribute_id"], ["extension_attributes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "extension_attribute_id"),
    )
    op.create_index("ix_device_ext_attr_device_id", "device_extension_attribute_values", ["device_id"], unique=False)
    op.create_table(
        "mobile_app_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mobile_app_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "APPLIED",
                "FAILED",
                "REVOKE_PENDING",
                "REVOKED",
                name="assignmentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "desired_state",
            sa.Enum("PRESENT", "ABSENT", name="assignmentdesiredstate", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("message_id", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["mobile_app_id"], ["mobile_apps.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("mobile_app_id", "version", "device_id"),
    )
    op.create_index("ix_mobile_app_assignments_device_id", "mobile_app_assignments", ["device_id"], unique=False)
    op.create_index(
        "ix_mobile_app_assignments_mobile_app_id", "mobile_app_assignments", ["mobile_app_id"], unique=False
    )
    op.create_table(
        "profile_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "SENT",
                "APPLIED",
                "FAILED",
                "REVOKE_PENDING",
                "REVOKED",
                name="assignmentstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "desired_state",
            sa.Enum("PRESENT", "ABSENT", name="assignmentdesiredstate", native_enum=False, length=10),
            nullable=False,
        ),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("message_id", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "profile_version", "device_id"),
    )
    op.create_index("ix_profile_assignments_device_id", "profile_assignments", ["device_id"], unique=False)
    op.create_index("ix_profile_assignments_profile_id", "profile_assignments", ["profile_id"], unique=False)
    op.create_table(
        "static_group_devices",
        sa.Column("static_group_id", sa.Integer(), nullable=False),
        sa.Column("device_serial_number", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["device_serial_number"], ["devices.serial_number"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["static_group_id"], ["static_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("static_group_id", "device_serial_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("static_group_devices")
    op.drop_index("ix_profile_assignments_profile_id", table_name="profile_assignments")
    op.drop_index("ix_profile_assignments_device_id", table_name="profile_assignments")
    op.drop_table("profile_assignments")
    op.drop_index("ix_mobile_app_assignments_mobile_app_id", table_name="mobile_app_assignments")
    op.drop_index("ix_mobile_app_assignments_device_id", table_name="mobile_app_assignments")
    op.drop_table("mobile_app_assignments")
    op.drop_index("ix_device_ext_attr_device_id", table_name="device_extension_attribute_values")
    op.drop_table("device_extension_attribute_values")
    op.drop_table("static_groups")
    op.drop_index("ix_smart_groups_created_by", table_name="smart_groups")
    op.drop_table("smart_groups")
    op.drop_index("ix_profiles_created_by", table_name="profiles")
    op.drop_table("profiles")
    op.drop_table("mobile_apps")
    op.drop_index("ix_inventory_searches_created_by", table_name="inventory_searches")
    op.drop_table("inventory_searches")
    op.drop_index("ix_extension_attributes_created_by", table_name="extension_attributes")
    op.drop_table("extension_attributes")
    op.drop_index("ix_commands_status", table_name="commands")
    op.drop_index("ix_commands_device_id", table_name="commands")
    op.drop_index("ix_commands_command_type", table_name="commands")
    op.drop_table("commands")
    op.drop_table("users")
    op.drop_index("ix_devices_status", table_name="devices")
    op.drop_index("ix_devices_os_version", table_name="devices")
    op.drop_index("ix_devices_connection_status", table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
